// <auto-generated />
using System;
using CartService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CartService.Migrations
{
    [DbContext(typeof(CartContext))]
    [Migration("20230131234012_MigrationMySqlInit")]
    partial class MigrationMySqlInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("CartService.Model.SessionCart", b =>
                {
                    b.Property<int>("SessionCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SessionCartId");

                    b.ToTable("SessionCart");
                });

            modelBuilder.Entity("CartService.Model.SessionCartDetail", b =>
                {
                    b.Property<int>("SessionCartDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Product")
                        .HasColumnType("longtext");

                    b.Property<int>("SessionCartId")
                        .HasColumnType("int");

                    b.HasKey("SessionCartDetailId");

                    b.HasIndex("SessionCartId");

                    b.ToTable("SessionCartDetail");
                });

            modelBuilder.Entity("CartService.Model.SessionCartDetail", b =>
                {
                    b.HasOne("CartService.Model.SessionCart", "SessionCart")
                        .WithMany("DetailList")
                        .HasForeignKey("SessionCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionCart");
                });

            modelBuilder.Entity("CartService.Model.SessionCart", b =>
                {
                    b.Navigation("DetailList");
                });
#pragma warning restore 612, 618
        }
    }
}
